# Generated by Django 2.1.5 on 2019-02-21 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('misc', '0001_initial'),
        ('organization', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('playbook', models.CharField(max_length=128)),
                ('limit', models.CharField(blank=True, max_length=64, null=True)),
                ('forks', models.IntegerField(default=5)),
                ('verbosity', models.IntegerField(default=2)),
                ('job_tags', models.CharField(max_length=128)),
                ('extra_variables', models.TextField()),
                ('allow_callback', models.BooleanField(default=False)),
                ('job_type', models.IntegerField(choices=[(1, '运行'), (2, '检查')])),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('url', models.URLField()),
                ('branch', models.CharField(blank=True, default='master', max_length=32, null=True)),
                ('revision', models.CharField(blank=True, max_length=32, null=True)),
                ('username', models.CharField(blank=True, max_length=32)),
                ('scm_type', models.IntegerField(choices=[(1, 'git')])),
                ('playbook_files', models.TextField(blank=True, default=',', null=True)),
                ('last_sync_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.Job')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('roles', models.ManyToManyField(to='misc.Role')),
            ],
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='roles',
            field=models.ManyToManyField(to='misc.Role'),
        ),
    ]
