# Generated by Django 2.1.5 on 2019-02-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtemplate',
            name='job_type',
            field=models.IntegerField(choices=[(1, '实际执行'), (2, '伪执行')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='playbook_files',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
