# Generated by Django 2.1.5 on 2019-02-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190225_1611'),
        ('project', '0002_auto_20190225_1624'),
    ]

    operations = [
    ]
