# Generated by Django 2.1.5 on 2019-02-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='owned_roles',
            field=models.ManyToManyField(related_name='owner_teams', to='misc.Role'),
        ),
    ]
