# Generated by Django 2.1.5 on 2019-02-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('extra_variables', models.TextField(null=True)),
                ('result', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
