# Generated by Django 2.1.5 on 2019-02-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=32)),
                ('resource_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=32)),
                ('display_name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('resource_type', 'resource_id', 'name')},
        ),
    ]
